# MODULE: 55-Export-Txt.ps1
# Експорт BRAVO SYSTEM REPORT у простий plain-text summary (v0.6.0 Reports
# and UX — TXT summary, той самий файл слугує й "copy-friendly support
# summary": легко вставити у тікет підтримки/Redmine без форматування).

function Export-BravoTxtReport {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [string]$OutputDir,

        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [string]$BaseFileName,

        [Parameter(Mandatory = $true)]
        [bool]$TXT
    )

    if (-not $TXT) { return }

    try {
        $txtPath = Join-Path $OutputDir "$BaseFileName.txt"
        $lines = [System.Collections.Generic.List[string]]::new()

        $lines.Add('=== BRAVO SYSTEM REPORT — SUMMARY ===')
        $lines.Add('')
        $lines.Add("Computer:      $($script:Report.ComputerName)")
        $lines.Add("Profile:       $($script:Report.Profile)")
        $lines.Add("Timestamp:     $($script:Report.Timestamp)")
        $lines.Add("Health Score:  $($script:Report.Health.Score)/100")
        $lines.Add("Status:        $($script:Report.Status)")
        $lines.Add("Status reason: $($script:Report.StatusReason)")
        $lines.Add('')

        $lines.Add('--- Key metrics ---')
        $lines.Add("OS:            $($script:Report.OS.Caption) ($($script:Report.OS.Version), build $($script:Report.OS.Build))")
        $lines.Add("Uptime:        $($script:Report.OS.UptimeDays)d $($script:Report.OS.UptimeHours)h")
        $lines.Add("CPU:           $($script:Report.Hardware.CPU.Name) — load $($script:Report.Hardware.CPU.LoadPercent)%")
        $lines.Add("RAM:           $($script:Report.Hardware.RAM.UsedGB) GB used / $($script:Report.Hardware.RAM.TotalGB) GB total ($($script:Report.Hardware.RAM.UsedPercent)%)")
        $lines.Add("Disk:          $($script:Report.Hardware.Disks.FreeGB) GB free / $($script:Report.Hardware.Disks.TotalGB) GB total ($($script:Report.Hardware.Disks.FreePercent)% free)")
        $lines.Add('')

        # Findings через ту саму чисту функцію групування, що й HTML-звіт
        # (src/40-Health.ps1, PR #82) — єдина точка сортування/лічильників
        # для всіх форматів звіту.
        $findingsGrouped = Get-BravoFindingsGrouped -Findings $script:Report.Health.Findings
        $lines.Add("--- Findings (Critical: $($findingsGrouped.CriticalCount), Warning: $($findingsGrouped.WarningCount), Info: $($findingsGrouped.InfoCount)) ---")

        if (@($findingsGrouped.Sorted).Count -gt 0) {
            foreach ($finding in @($findingsGrouped.Sorted)) {
                $lines.Add("$($finding.Severity) | $($finding.Category) | $($finding.Message)")
            }
        } else {
            $lines.Add('Критичних зауважень не знайдено.')
        }
        $lines.Add('')

        $collectionErrorCount = @($script:Report.CollectionErrors).Count
        if ($collectionErrorCount -gt 0) {
            $lines.Add("--- Collection errors ($collectionErrorCount) ---")
            foreach ($collectionError in @($script:Report.CollectionErrors)) {
                $lines.Add("$($collectionError.Section) | $($collectionError.Message)")
            }
            $lines.Add('')
        }

        $lines.Add("Generated by BRAVO SYSTEM REPORT v$($script:Report.ScriptVersion) (SchemaVersion $($script:Report.SchemaVersion))")

        Set-Content -LiteralPath $txtPath -Value $lines -Encoding utf8
        $script:Report.GeneratedFiles += $txtPath
        Write-Host "  $IconCsv TXT: $BaseFileName.txt" -ForegroundColor Green
    } catch {
        Add-ExportError -Section 'Export.Txt' -Message $_.Exception.Message
        Write-Host "  $IconError Помилка TXT: $($_.Exception.Message)" -ForegroundColor Red
    }
}
