# MODULE: 56-Export-Md.ps1
# Експорт BRAVO SYSTEM REPORT у Markdown summary (v0.6.0 Reports and UX —
# Markdown summary для Redmine/GitHub). Той самий набір даних, що й TXT
# summary (src/55-Export-Txt.ps1), але з Markdown-розміткою: заголовки,
# таблиця ключових метрик, таблиця findings — щоб можна було вставити прямо
# в опис issue/тікета й отримати відформатований вивід.

function Export-BravoMdReport {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [string]$OutputDir,

        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [string]$BaseFileName,

        [Parameter(Mandatory = $true)]
        [bool]$MD
    )

    if (-not $MD) { return }

    try {
        $mdPath = Join-Path $OutputDir "$BaseFileName.md"
        $lines = [System.Collections.Generic.List[string]]::new()

        $lines.Add('# BRAVO SYSTEM REPORT — Summary')
        $lines.Add('')
        $lines.Add("**Computer:** $($script:Report.ComputerName)  ")
        $lines.Add("**Profile:** $($script:Report.Profile)  ")
        $lines.Add("**Timestamp:** $($script:Report.Timestamp)  ")
        $lines.Add("**Health Score:** $($script:Report.Health.Score)/100  ")
        $lines.Add("**Status:** $($script:Report.Status)  ")
        $lines.Add("**Status reason:** $($script:Report.StatusReason)")
        $lines.Add('')

        $lines.Add('## Key metrics')
        $lines.Add('')
        $lines.Add('| Metric | Value |')
        $lines.Add('|---|---|')
        $lines.Add("| OS | $($script:Report.OS.Caption) ($($script:Report.OS.Version), build $($script:Report.OS.Build)) |")
        $lines.Add("| Uptime | $($script:Report.OS.UptimeDays)d $($script:Report.OS.UptimeHours)h |")
        $lines.Add("| CPU | $($script:Report.Hardware.CPU.Name) — load $($script:Report.Hardware.CPU.LoadPercent)% |")
        $lines.Add("| RAM | $($script:Report.Hardware.RAM.UsedGB) GB used / $($script:Report.Hardware.RAM.TotalGB) GB total ($($script:Report.Hardware.RAM.UsedPercent)%) |")
        $lines.Add("| Disk | $($script:Report.Hardware.Disks.FreeGB) GB free / $($script:Report.Hardware.Disks.TotalGB) GB total ($($script:Report.Hardware.Disks.FreePercent)% free) |")
        $lines.Add('')

        # Findings через ту саму чисту функцію групування, що й TXT/HTML-звіт
        # (src/40-Health.ps1, PR #82) — єдина точка сортування/лічильників
        # для всіх форматів звіту.
        $findingsGrouped = Get-BravoFindingsGrouped -Findings $script:Report.Health.Findings
        $lines.Add("## Findings (Critical: $($findingsGrouped.CriticalCount), Warning: $($findingsGrouped.WarningCount), Info: $($findingsGrouped.InfoCount))")
        $lines.Add('')

        if (@($findingsGrouped.Sorted).Count -gt 0) {
            $lines.Add('| Severity | Category | Message |')
            $lines.Add('|---|---|---|')
            foreach ($finding in @($findingsGrouped.Sorted)) {
                $escapedMessage = $finding.Message -replace '\|', '\|'
                $lines.Add("| $($finding.Severity) | $($finding.Category) | $escapedMessage |")
            }
        } else {
            $lines.Add('Критичних зауважень не знайдено.')
        }
        $lines.Add('')

        $collectionErrorCount = @($script:Report.CollectionErrors).Count
        if ($collectionErrorCount -gt 0) {
            $lines.Add("## Collection errors ($collectionErrorCount)")
            $lines.Add('')
            $lines.Add('| Section | Message |')
            $lines.Add('|---|---|')
            foreach ($collectionError in @($script:Report.CollectionErrors)) {
                $escapedMessage = $collectionError.Message -replace '\|', '\|'
                $lines.Add("| $($collectionError.Section) | $escapedMessage |")
            }
            $lines.Add('')
        }

        $lines.Add("*Generated by BRAVO SYSTEM REPORT v$($script:Report.ScriptVersion) (SchemaVersion $($script:Report.SchemaVersion))*")

        Set-Content -LiteralPath $mdPath -Value $lines -Encoding utf8
        $script:Report.GeneratedFiles += $mdPath
        Write-Host "  $IconCsv MD: $BaseFileName.md" -ForegroundColor Green
    } catch {
        Add-ExportError -Section 'Export.Md' -Message $_.Exception.Message
        Write-Host "  $IconError Помилка MD: $($_.Exception.Message)" -ForegroundColor Red
    }
}
